announce = false
description = 'alt:V'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'pt'
modules = [ 'js-module' ]
name = 'alt:V Server'
players = 128
port = 7788
debug = true
resources = [ 'core' ]
website = 'example.com'